# Generated by Django 6.0.6 on 2026-06-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(help_text='Direct link to team banner/logo poster', max_length=500)),
                ('budget', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12)),
                ('captain_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(help_text='Direct link to player profile image', max_length=500)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('CMF', 'Central Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('UNSOLD', 'Unsold'), ('BIDDING', 'Bidding'), ('SOLD', 'Sold')], default='UNSOLD', max_length=10)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='auction.team')),
            ],
        ),
    ]
