# Generated by Django 6.0.6 on 2026-06-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='team',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
    ]
