# Generated by Django 6.0.6 on 2026-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_player_base_amount_alter_team_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='placeholder.png', help_text='Upload player photo from system storage', upload_to='players/profiles/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='captain_image',
            field=models.ImageField(default='staff/default-avatar.png', upload_to='staff/captains/'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='placeholder.png', help_text='Upload team logo/poster from system storage', upload_to='teams/logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='manager_image',
            field=models.ImageField(default='staff/default-avatar.png', upload_to='staff/managers/'),
        ),
    ]
